# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 663a5bf4ce6d3b79cd8f7e8d5088e5b92b950413135d49ae6ccb6a61a0ed6e0426bf7f527932516f16723d0258641050feb99ecce3c5d3fe1c7e30487c2eff68

test:
  secret_key_base: 6b7310f3dca1a2745d3338334d544d6b6394b1a30dca6066c71d1f578aedb0d1fb5e0957bca4f6b9a645adadc3aeee544b4e63510e21f1fac7944a5dc52bb679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
